# Generated by Django 3.0.5 on 2020-04-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
            ],
            options={
                'db_table': 'buku',
            },
        ),
    ]
